apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-frontend
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/name: rag-frontend
    app.kubernetes.io/part-of: enterprise-agentic-rag
spec:
  rules:
    - host: rag.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-frontend
                port:
                  name: http
