apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - service-account.yaml
  - secret-provider-class.yaml

images:
  - name: enterprise-agentic-rag-backend
    newName: REPLACE_WITH_ACR_LOGIN_SERVER/enterprise-agentic-rag-backend
    newTag: REPLACE_WITH_GIT_SHA
  - name: enterprise-agentic-rag-frontend
    newName: REPLACE_WITH_ACR_LOGIN_SERVER/enterprise-agentic-rag-frontend
    newTag: REPLACE_WITH_GIT_SHA

patches:
  - path: backend-patch.yaml
  - path: ingress-patch.yaml
